import type { Metadata } from "next";
import "./global.css";
import Header from "@/components/Header";
import Auth from "@/auth/Auth";
import FormProvider from "@/contexts/Form";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="pt-br">
      <body className="bg-light dark:bg-dark flex w-screen h-screen">
        <FormProvider>
          <Auth>
            <>
              <Header />
              {children}
            </>
          </Auth>
        </FormProvider>
      </body>
    </html>
  );
}